/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm32l4xx.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#define GPIOAEN   (1U << 0)
#define GPIOCEN   (1U << 2)

#define PIN5      (1U<<5)
#define PIN13	  (1U << 13)

#define LED_PIN   PIN5
#define BTN_PIN	  PIN13

int main()
{
	RCC->AHB2ENR |= GPIOAEN;
	RCC->AHB2ENR |= GPIOCEN;


	GPIOA -> MODER |= (1U<<10);
	GPIOA -> MODER &= ~(1U << 11);

	GPIOC->MODER &= ~((1U<<26) | (1U <<27));
	while(1)
	{
		if(!(GPIOC -> IDR & BTN_PIN))
		{
			GPIOA -> BSRR = LED_PIN;
		}
		else
		{
			GPIOA -> BSRR = (1<<21);
		}
	}
}


