/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32l476xx.h"
#include "i2c_master.h"
#include <string.h>

uint8_t tx[] = "HELLO_ESP32";
uint8_t rx[20];

int main(void)
{
    I2C1_GPIO_Init();
    I2C1_Init();
    I2C1_Interrupt_Init();

    // Send data to ESP32
    I2C1_Master_Transmit_IT(0x28, tx, strlen((char*)tx));
    while (I2C1_Handle.state != I2C_READY);

    // Receive reply from ESP32
    I2C1_Master_Receive_IT(0x28, rx, 9);
    while (I2C1_Handle.state != I2C_READY);

    while(1);
}
